"""keyset index on trials

Revision ID: 5b72dceb5d13
Revises: a209ff92d3a3
Create Date: 2026-08-15 23:39:57.559183
"""
from collections.abc import Sequence

from alembic import op

revision: str = '5b72dceb5d13'
down_revision: str | None = 'a209ff92d3a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trials_created_at_id', 'trials', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trials_created_at_id', table_name='trials')
    # ### end Alembic commands ###
