"""initial schema

Revision ID: a209ff92d3a3
Revises: 
Create Date: 2026-08-15 20:33:56.775729
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a209ff92d3a3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='patient_sex'), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('lab_values', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_external_id'), 'patients', ['external_id'], unique=True)
    op.create_table('trials',
    sa.Column('nct_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RECRUITING', 'ACTIVE_NOT_RECRUITING', 'COMPLETED', 'TERMINATED', name='trial_status'), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trials_nct_id'), 'trials', ['nct_id'], unique=True)
    op.create_index(op.f('ix_trials_status'), 'trials', ['status'], unique=False)
    op.create_index('ix_trials_status_phase', 'trials', ['status', 'phase'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'COORDINATOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('criteria_nodes',
    sa.Column('trial_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('node_type', sa.Enum('AND', 'OR', 'NOT', 'LEAF', name='node_type'), nullable=False),
    sa.Column('is_exclusion', sa.Boolean(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.Enum('EQ', 'NEQ', 'GT', 'GTE', 'LT', 'LTE', 'IN', 'CONTAINS', name='criteria_operator'), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['criteria_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteria_nodes_parent_id'), 'criteria_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_criteria_nodes_trial_id'), 'criteria_nodes', ['trial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_criteria_nodes_trial_id'), table_name='criteria_nodes')
    op.drop_index(op.f('ix_criteria_nodes_parent_id'), table_name='criteria_nodes')
    op.drop_table('criteria_nodes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_trials_status_phase', table_name='trials')
    op.drop_index(op.f('ix_trials_status'), table_name='trials')
    op.drop_index(op.f('ix_trials_nct_id'), table_name='trials')
    op.drop_table('trials')
    op.drop_index(op.f('ix_patients_external_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
